# -*- coding: utf-8 -*-
"""
Noise instance detection and subtype classification

This module combines the segmentation noise channel with a ResNet-18 classifier to identify and categorize non-textual marks. It extracts bounding boxes from the noise mask, crops the original RGB image, and applies a confidence-based reject option. Marks with confidence below the threshold are labeled as unknown to serve as retrieval wildcards
"""

import os
import dataclasses
from typing import List, Any, Tuple

import numpy as np
from PIL import Image
import torch
import torchvision.transforms.functional as TF
from torchvision.transforms import Normalize

from src.core.config import get_artifact_dir
from src.core.confidence import DEFAULT_UNKNOWN_TAU, LABEL_UNKNOWN
from src.detection.noise.bbox import extract_noise_bboxes
from src.detection.noise.classifier import build_classifier, SIZE_INPUT, predict_crop

BASE_PATH = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
DATA_DIR = os.path.join(BASE_PATH, "data")
STORAGE_DIR = os.path.join(BASE_PATH, "storage")

IDX_NS_CHANNEL = 0
NORM_TRANSFORM = Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225))

@dataclasses.dataclass
class NoiseInstance:
    """
    Data structure representing a detected noise object

    Attributes:
        mark_id (str): Unique identifier for the mark
        bbox (List[int]): Spatial coordinates in xywh pixel format
        mark_type (str): Categorical label for the noise subtype
        confidence_score (float): Probability score from the classifier
        description (str): Optional prose description generated by VLM
    """
    mark_id: str
    bbox: List[int]
    mark_type: str
    confidence_score: float
    description: str = ""

def load_model(model_name: str = "noise_resnet", checkpoint_path: str = None, device: Any = None):
    """
    Load the ResNet-18 noise classifier from a weight file

    Args:
        model_name (str): Identifier for the model architecture
        checkpoint_path (str): Explicit path to a weight file
        device (Any): Execution device for the model
    Returns:
        Tuple[Any, Any]: Initialized model and the active device
    """
    if device is None:
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    if checkpoint_path is None:
        checkpoint_path = os.path.join(get_artifact_dir("detection", model_name, "weights"), "best.pt")
    model = build_classifier(pretrained=False).to(device)
    ckpt = torch.load(checkpoint_path, map_location=device)
    model.load_state_dict(ckpt["model_state"])
    model.eval()
    return model, device

def predict_noise_instances(model, device: Any, page_np: np.ndarray, prob_ns: np.ndarray,
                            tau: float = DEFAULT_UNKNOWN_TAU, kernel: Tuple[int, int] = None,
                            threshold: float = None) -> List[NoiseInstance]:
    """
    Detect and classify all noise instances present on a single page

    The function identifies noise blobs and categorizes them using the provided classifier. It implements a reject option where low-confidence predictions are relabeled to maintain high precision in specific mark categories
    Args:
        model (Any): Initialized ResNet-18 classifier model
        device (Any): Execution device for the model
        page_np (np.ndarray): Original RGB page data
        prob_ns (np.ndarray): Probability channel for the noise layer
        tau (float): Confidence threshold for the reject option
        kernel (Tuple[int, int]): Kernel size for RLSA region extraction
        threshold (float): Binarization threshold for the probability map
    Returns:
        List[NoiseInstance]: Collection of detected and classified noise objects
    """
    if kernel is not None:
        from src.detection.region.extract import extract_regions
        kw = {} if threshold is None else {"threshold": threshold}
        regions = extract_regions(prob_ns, prefix="ns", kernel=kernel, **kw)
        bboxes = [r.bbox for r in regions]
    else:
        kw = {} if threshold is None else {"threshold": threshold}
        bboxes = extract_noise_bboxes(prob_ns, **kw)

    page_pil = Image.fromarray(page_np)
    instances = []

    for i, (x, y, w, h) in enumerate(bboxes):
        crop = page_pil.crop((x, y, x + w, y + h)).resize((SIZE_INPUT, SIZE_INPUT), Image.BILINEAR)
        crop_t = NORM_TRANSFORM(TF.to_tensor(crop).unsqueeze(0))
        mark_type, conf = predict_crop(model, crop_t, device)
        if conf < tau:
            mark_type = LABEL_UNKNOWN
        instances.append(NoiseInstance(
            mark_id=f"mark_{i:04d}",
            bbox=[x, y, w, h],
            mark_type=mark_type,
            confidence_score=conf,
        ))

    return instances
